services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regression-tests
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    command: sh -c "pytest -sv --alluredir=allure-results && allure generate allure-results --clean -o allure-report"
    volumes:
      - ./allure-results:/usr/workspace/allure-results:rw
      - ./allure-report:/usr/workspace/allure-report:rw
    user: root