services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regression-tests
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}