services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regression-tests
    volumes:
      - ./:/usr/workspace:rw
    command: sh -c "pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}