name: CI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Run CI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression --abort-on-container-exit || true

      - name: Generate Allure report
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          mkdir -p allure-report
          
          docker cp $(docker-compose ps -q regression):/app/allure-results ./allure-results/ || true
          
          docker run --rm \
            -v "$PWD/allure-results:/allure-results" \
            -v "$PWD/allure-report:/allure-report" \
            allure-commandline/allure:latest \
            generate /allure-results --clean -o /allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.AQA_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true